### PR TITLE
Try to exclude all non electric cars

### PR DESCRIPTION
**Pull request by doscit01**
Hi Mitch,

i've tried to exclude cars that have no 'fuel-status' in their domains from the list. 
This worked for me with my Tiguan and ID.3. My Tiguan will run the exception clause whereas my ID.3 will run the try clause through and i have no error in the start of home_assistant. If you like i could reset my changed environment to make the exception clause a bit or narrow, but i think for future stability this will just catch all issues.

regards

Dominik

### CODE REVIEW

**Comment by mitch-dc** [comment]
Thanks for the suggestion, i don't have an ICE volkswagen so it is hard to figure stuff like this out ;) 

I don't think relying on the try/catch method is the best option (it does work but still) what value do you get from car type on your tiguan?

`    class CarType(Enum,):
        ELECTRIC = 'electric'
        HYBRID = 'hybrid'
        GASOLINE = 'gasoline'
        PETROL = 'petrol'
        CNG = 'cng'
        LPG = 'lpg'
        INVALID = 'invalid'
        UNKNOWN = 'unknown car type'
`

**Comment by doscit01** [comment]
Hi Mitch,

I think the last that i saw said MISSING for 'fuel-status', but i'll check when i'm back home.

Regards

Dominik

**Comment by doscit01** [comment]
Hi Mitch, this is what i get if i just print:
2022-02-16 14:30:07 INFO (MainThread) [custom_components.volkswagen_we_connect_id] Domains: [[[capabilitiesStatus]
Capabilities: 50 items
[access] Status: MISSING_SERVICE disabling: False
[automation] Status: MISSING_SERVICE disabling: False
[charging] Status: MISSING_SERVICE disabling: False
[climatisation] Status: MISSING_SERVICE disabling: False
[cubicNetwork] Status: MISSING_SERVICE disabling: False
[cubicNetworkConsumption] Status: MISSING_SERVICE disabling: False
[dealerAppointment] Status: MISSING_SERVICE disabling: False
[destinationSync] Status: MISSING_SERVICE disabling: False
[digitalKey] Status: MISSING_SERVICE disabling: False
[emergencyCalling] Status: MISSING_SERVICE disabling: False
[fuelStatus] Status: MISSING_SERVICE disabling: False
[geofence] Status: MISSING_SERVICE disabling: False
[googleEarth] Status: MISSING_SERVICE disabling: False
[hybridRadio] Status: MISSING_SERVICE disabling: False
[informationCall] Status: MISSING_SERVICE disabling: False
[mapUpdate] Status: MISSING_SERVICE disabling: False
[measurements] Status: MISSING_SERVICE disabling: False
[mobileDeviceKey] Status: MISSING_SERVICE disabling: False
[news] disabling: False
[oilLevelStatus] Status: MISSING_SERVICE disabling: False
[onlineSpeech] Status: MISSING_SERVICE disabling: False
[parkingInformation] disabling: False
[parkingPosition] Status: MISSING_SERVICE disabling: False
[roadsideAssistant] Status: MISSING_SERVICE disabling: False
[routing] Status: MISSING_SERVICE disabling: False
[speedAlert] Status: MISSING_SERVICE disabling: False
[state] Status: MISSING_SERVICE disabling: False
[theftWarning] Status: MISSING_SERVICE disabling: False
[transactionHistoryAntiTheftAlert] Status: MISSING_SERVICE disabling: False
[transactionHistoryAntiTheftAlertDelete] Status: MISSING_SERVICE disabling: False
[transactionHistoryDigitalKey] Status: MISSING_SERVICE disabling: False
[transactionHistoryGeofence] Status: MISSING_SERVICE disabling: False
[transactionHistoryGeofenceDelete] Status: MISSING_SERVICE disabling: False
[transactionHistoryHonkFlash] Status: MISSING_SERVICE disabling: False
[transactionHistoryLockUnlock] Status: MISSING_SERVICE disabling: False
[transactionHistorySpeedAlert] Status: M....

there are a lot more and some of them actually have values, but the majority are flagged as MISSING_SERVICE
Let me try to use that instead of the exception

regards

Dominik

**Comment by doscit01** [comment]
So all the objects in domains don'T show any sign of a type of car. I'll setup a debug environment and see if i can find a clear destinction. But i think as the 'older' cars use more or less another version of the api that they lack certain objects. Hopefully the structure for the ID cars will stay the same.

regards

Dominik

**Comment by doscit01** [comment]
Hi Mitch i've been able to debug the whoe thing and i think i've come up with the simplest sollution to scan for ID cars

regards

Dominik

**Comment by doscit01** [comment]
Hi Mitch,
do you want to merge the PR into your main? Otherwise i will just close the PR and branch off your repo into my own space to keep track of your improvements and easily be able to merge mine always back into your main. I think it would be a bummer if i would just close this PR, but it's up to you to use the latest version i made. I think checking the model name for ID is the most simple sollution as every car has a model name as attribute. But again, up to you.

regards

Dominik

**Comment by mitch-dc** [comment]
Based on your suggestion ive added a better way to check for ID cars :) thanks!

**Comment by doscit01** [comment]
Hi Mitch, thx for the feedback. Your adaption using an array of possibilities look quite good.thx, i'll close this one now.

regards

Dominik

**Pull request closed without merging**
