### PR TITLE
Make the update interval configurable, defaulting to every 5 mins

### PR DESCRIPTION
**Pull request by tsg21**
The integration currently updates every 30s. I propose that this is excessively frequent:
1. I suspect VW expected calls to this API perhaps 10 times per day per user. It's designed to back the app. Calling it 2880 times a day is a lot. If a lot of people use this integration it's going to cause a lot of unexpected traffic for the backend that serves this up. I would not be surprised if they started throttling frequent callers.
2. I don't think there's any real benefit to updating more than about every 5 mins. The values do not change frequently enough to matter.

What do you think?

### CODE REVIEW

**Comment by chrjsorg** [comment]
Another option: Make it configurable (30-600s) maybe

**Comment by tsg21** [comment]
That would make sense if there was a good reason to want to change it, but is there? I cannot see a reason to want updates more frequently than every 5 mins. Am I missing something?

**Comment by gkrallo** [comment]
KiaEV6 do have limitations and a very bad one, it cause there own app to stop work if you ask too many times a day, resets everyday.

**Comment by frederoni** [comment]
I use this plugin to automatically stop charging when the hourly kWh price goes over a certain threshold. Having 5 minutes could make charging a bit more expensive for me. If it was customizable, I think I would put it at 1-2 minutes.

**Comment by whohencode** [comment]
> I use this plugin to automatically stop charging when the hourly kWh price goes over a certain threshold. Having 5 minutes could make charging a bit more expensive for me. If it was customizable, I think I would put it at 1-2 minutes.

(I also use this to control my charging @frederoni but if you miss the spot price increase/decrease with 5min that should only translate to "a couple of öre")

**Comment by tsg21** [comment]
okay, so maybe it should default to every 5 mins, but allow that to be upped to every 1 min through configuration.

**Comment by mitch-dc** [comment]
I do not agree with the 5 minute. 
Then you can have a 5 minute delay with the notification that the car started or stopped charging.

**Comment by tsg21** [comment]
@mitch-dc OK. I have no need for that information to be precise, but you clearly do.

It seems we should make it configurable then, as I am a little comfortable with my credentials spamming the VW endpoint. I will see if I can make that change.

**Comment by tsg21** [comment]
I've attempted to make the update interval configurable, but for some reason no configuration options are appearing for me at all in the UI. What have I done wrong?

**Comment by JelleKoster** [comment]
Perhaps a middle ground could be to both have a configurable interval as well as an added GET API call to retrieve the latest information after we change something?
For example, after I use the service to start charging I want confirmation whether it actually has started charging.
This of course doesn't help with car-initiated state changes, but it should mitigate the amount of scenarios facing delays due to a longer interval.

**Comment by tsg21** [comment]
Yes, it would be reasonable to have a short poll interval while the car is thought to be active, then go a longer poll when it is just parked/off/inactive.

**Comment by Maxi531** [comment]
I have a question regarding the polling interval. In normal VW cars, the server will just respond with its last known values if the car goes into "sleep" and you have to willingly force it to wake up. If the same is happening with the ID Cars, a change in polling interval would not be that bad for the times your car is just sitting around, considering there is no new info to get anyway

**Review by mediaguycouk — APPROVED** [review]

**Comment by pdcastro** [comment]
> _I've attempted to make the update interval configurable, but for some reason no configuration options are appearing for me at all in the UI. [...] What have I done wrong?_

The smallest diff that made it work for me was to replace:

```python
vol.Optional("update_interval"): vol.Range(min=MINIMUM_UPDATE_INTERVAL_SECONDS)
```

with:

```python
vol.Optional("update_interval"): vol.All(int, vol.Range(min=MINIMUM_UPDATE_INTERVAL_SECONDS))
```

I don’t know why this change makes a significant difference. It might as well be a bug in [voluptuous](https://pypi.org/project/voluptuous/). 🤷

As this PR has been parked for more than a year, and another reason appears to be that the author and the maintainer have not converged on a default update interval value, I decided to create a new PR that fixes the issue above and preserves the existing 45-second update interval as the default value of the configurable option: #247 [Make the update interval configurable](https://github.com/mitch-dc/volkswagen_we_connect_id/pull/247)

**Pull request closed without merging**
